var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v7jt~1._.js")
R.c("server/chunks/ssr/0~q1_next_dist_esm_build_templates_app-page_0dbssrr.js")
R.c("server/chunks/ssr/[root-of-the-server]__13ah53k._.js")
R.c("server/chunks/ssr/[root-of-the-server]__05.o69z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__07hot7e._.js")
R.c("server/chunks/ssr/0~q1_next_dist_client_components_0gzzaqo._.js")
R.c("server/chunks/ssr/0~q1_next_dist_client_components_builtin_forbidden_03mc96n.js")
R.c("server/chunks/ssr/0~q1_next_dist_client_components_builtin_unauthorized_0464z.8.js")
R.c("server/chunks/ssr/Desktop_pitch_GNF__next-internal_server_app__not-found_page_actions_07qvhak.js")
R.m(50168)
module.exports=R.m(50168).exports
