import Link from 'next/link'
import { Globe2, Mail, MapPin, MessageCircle, Send, Video } from 'lucide-react'

export default function Footer() {
  const locale = 'en'
  const links = [['Medical Billing Services', '/billing-services'], ['Practice Care', '/billing-services/practice-care'], ['Billing Care', '/billing-services/billing-care'], ['Billing Care Plus', '/billing-services/billing-care-plus']]
  const solutions = [['OHIP Billing', '/solutions/ohip-billing'], ['MSP Billing', '/solutions/msp-billing'], ['AHCIP Billing', '/solutions/ahcip-billing'], ['Other Provinces', '/solutions/other-provinces']]
  return <footer id="contact" className="bg-[#241321] text-white"><div className="mx-auto max-w-7xl px-6 py-16 lg:px-8"><div className="grid gap-12 md:grid-cols-2 lg:grid-cols-[1.3fr_1fr_1fr_1.1fr]"><div><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-xl font-bold text-[#7e0e58]">+</span><span className="text-xl font-extrabold">GNF<span className="text-[#e6b4d6]">Billing</span></span></div><p className="mt-5 max-w-xs text-sm leading-6 text-white/65">Billing support and practice optimization designed around Canadian physicians.</p><div className="mt-6 flex gap-3">{[Globe2, MessageCircle, Send, Video].map((Icon, i) => <a href="#" key={i} aria-label="Social link" className="rounded-full border border-white/15 p-2 text-white/70 hover:bg-white/10 hover:text-white"><Icon size={16}/></a>)}</div></div><div><h3 className="text-sm font-bold uppercase tracking-wider text-[#e6b4d6]">Services</h3><div className="mt-5 grid gap-3">{links.map(([title, href]) => <Link key={href} href={`/${locale}${href}`} className="text-sm text-white/70 hover:text-white">{title}</Link>)}</div></div><div><h3 className="text-sm font-bold uppercase tracking-wider text-[#e6b4d6]">Solutions</h3><div className="mt-5 grid gap-3">{solutions.map(([title, href]) => <Link key={href} href={`/${locale}${href}`} className="text-sm text-white/70 hover:text-white">{title}</Link>)}</div></div><div><h3 className="text-sm font-bold uppercase tracking-wider text-[#e6b4d6]">Get in touch</h3><p className="mt-5 flex gap-3 text-sm leading-6 text-white/70"><Mail size={17} className="mt-0.5 shrink-0"/>info@gnfbilling.ca</p><p className="mt-3 flex gap-3 text-sm leading-6 text-white/70"><MapPin size={17} className="mt-0.5 shrink-0"/>Supporting physicians across Canada</p><Link href="#contact" className="mt-6 inline-flex rounded-full border border-white/30 px-4 py-2 text-sm font-bold hover:bg-white hover:text-[#241321]">Book a free assessment</Link></div></div><div className="mt-14 flex flex-col gap-3 border-t border-white/10 pt-6 text-xs text-white/45 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 GNF-Billing. All rights reserved.</p><div className="flex gap-5"><a href="#">Privacy Policy</a><a href="#">Terms of Use</a></div></div></div></footer>
}
