import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, CheckCircle2 } from 'lucide-react'
import Header from '@/components/header'
import Footer from '@/components/footer'

type PageContent = { eyebrow: string; title: string; intro: string; image: string; points: string[]; sectionTitle: string; sectionText: string }

const content: Record<string, PageContent> = {
  'billing-services': { eyebrow: 'Medical Billing Services', title: 'Medical billing services and solutions for every need.', intro: 'Whether you are a family physician, specialist, in a large practice or a small clinic, our billing management and practice optimization solutions take the stress out of billing.', image: '/medium-shot-smiley-doctor-holding-tablet.jpg', points: ['Find and recover missed revenue opportunities', 'Reduce errors before claims are submitted', 'Get clear reporting on how you are paid'], sectionTitle: 'Every medical billing need covered.', sectionText: 'We work with your EMR and billing workflow to help you maximize revenue, minimize errors, and free up more time for patient care.' },
  'billing-services/practice-care': { eyebrow: 'Practice Care', title: 'Optimize your practice with better billing insights.', intro: 'Practice Care gives primary care physicians the reporting, analytics, and billing automation they need to understand performance and act on opportunities.', image: '/woman-doctor-wearing-white-coat-with-stethoscope-with-smile-face-pointing-with-finger-side-standing-isolated-blue.jpg', points: ['Actionable insights for your practice', 'Bonus and revenue opportunity tracking', 'Simple, transparent monthly reporting'], sectionTitle: 'A clearer view of your practice.', sectionText: 'Move beyond complicated billing data with a practical view of revenue, performance, and priorities for your team.' },
  'billing-services/billing-care': { eyebrow: 'Billing Care', title: 'Automated billing submissions and error correction in your EMR.', intro: 'Billing Care takes the administrative burden of managing submissions and correcting billing errors out of your day-to-day workflow.', image: '/front-view-male-doctor-medical-suit-with-stethoscope-blue-surface.jpg', points: ['Works with your existing EMR workflow', 'Error reconciliation and resubmissions', 'Support for family physicians and specialists'], sectionTitle: 'Spend less time fixing billings.', sectionText: 'Our billing specialists help review, manage, and correct claims while your team stays focused on delivering care.' },
  'billing-services/billing-care-plus': { eyebrow: 'Billing Care Plus', title: 'A full-service billing partner for busy physicians.', intro: 'Let us take care of written day sheets, claim entry, error checking, and submissions while you retain a clear view of your revenue.', image: '/young-nurse-white-uniform-checks-patient-with-stethoscope-front-view.jpg', points: ['Claim entry from written day sheets', 'Thorough error checking before submission', 'Complete visibility into billing performance'], sectionTitle: 'Leave manual billing behind.', sectionText: 'Billing Care Plus is designed for physicians who need a dependable end-to-end billing service, including hospital-based practices.' },
  'billing-services/uninsured-medical-services': { eyebrow: 'Uninsured Medical Services', title: 'Make uninsured services simple to manage.', intro: 'A complete workflow for effectively managing uninsured medical services and the administrative work that comes with them.', image: '/young-nurse-face-mask-hand-gloves-checks-patient-with-stethoscope.jpg', points: ['Track uninsured services consistently', 'Clear, practice-friendly workflows', 'More time for patient care'], sectionTitle: 'A better uninsured services workflow.', sectionText: 'Bring clarity to the activities that fall outside provincial billing, without adding another complicated system to your practice.' },
  'solutions': { eyebrow: 'Solutions', title: 'Take your practice from good to great.', intro: 'Our solutions help physicians maximize revenue and streamline practice operations so more of the day can be spent on patient care.', image: '/front-view-male-doctor-medical-suit-with-stethoscope-blue-background-pandemic-covid-virus-hospital-vaccine-coronavirus-drug.jpg', points: ['Ontario, Alberta, BC, and other provinces', 'Billing management that fits your workflow', 'Dedicated support from billing specialists'], sectionTitle: 'Solutions built around your province.', sectionText: 'Every province has its own billing rules. Our team makes it easier to stay on top of the details and capture eligible revenue.' },
  'solutions/ohip-billing': { eyebrow: 'OHIP Billing', title: 'Never lose out on OHIP billing revenue again.', intro: 'OHIP billing is complex. We identify missed opportunities and make it easier to resolve errors, manage rosters, and optimize your practice revenue.', image: '/front-view-male-doctor-medical-suit-checking-his-body-with-stethoscope-blue-surface.jpg', points: ['Automated OHIP billing and error reconciliation', 'Roster management and outside-use monitoring', 'Bonus optimization and preventive care support'], sectionTitle: 'OHIP billing made more manageable.', sectionText: 'Whether you use an EMR or paper-based workflow, we help take time-consuming billing tasks off your team’s plate.' },
  'solutions/ohip-billing/discover-practice-care': { eyebrow: 'OHIP Billing · Practice Care', title: 'Discover what Practice Care can do for your practice.', intro: 'See your billing information clearly, understand monthly opportunities, and get the support to turn insights into action.', image: '/medium-shot-smiley-doctor-holding-tablet.jpg', points: ['Clear revenue and performance reporting', 'Prioritized recommendations each month', 'Better support for FHO and FHG practices'], sectionTitle: 'Turn billing data into action.', sectionText: 'Practice Care brings the essentials together in a format that makes it easier to keep your practice on track.' },
  'solutions/ohip-billing/transitioning-to-fho': { eyebrow: 'OHIP Billing · FHO', title: 'Make a confident transition to a FHO.', intro: 'Understand the FHO model, guide your transition, and build a more predictable approach to practice revenue.', image: '/woman-doctor-wearing-white-coat-with-stethoscope-with-smile-face-pointing-with-finger-side-standing-isolated-blue.jpg', points: ['Guidance before and throughout transition', 'Clear view of model requirements', 'Support for revenue and roster planning'], sectionTitle: 'Transition with the right support.', sectionText: 'Our specialists help physicians evaluate their options and prepare for a successful transition to a Family Health Organization.' },
  'solutions/ohip-billing/ohip-billing-services-for-specialists': { eyebrow: 'OHIP Billing · Specialists', title: 'Personalized billing services for specialists.', intro: 'Specialist billing requires focused expertise. We help reduce administrative burden and improve the accuracy of every claim.', image: '/front-view-male-doctor-medical-suit-with-stethoscope-blue-background-pandemic-covid-virus-hospital-vaccine-coronavirus-drug.jpg', points: ['Specialty-aware billing review', 'Accurate submissions and corrections', 'Hands-on revenue optimization support'], sectionTitle: 'More time for your specialty.', sectionText: 'Receive tailored support from billing experts who understand the unique complexity of specialist claims.' },
  'solutions/ohip-billing/physician-transition-services': { eyebrow: 'OHIP Billing · Transition Services', title: 'Plan your next practice move with confidence.', intro: 'Whether you are looking for locum work, joining a clinic, or taking over a practice, we help you understand the opportunity.', image: '/young-nurse-black-face-mask-checks-patient-with-stethoscope.jpg', points: ['Practice opportunity guidance', 'Revenue and billing transition support', 'A smoother path into your next role'], sectionTitle: 'Support for your next chapter.', sectionText: 'Make informed decisions about your professional transition with experienced, practical support.' },
  'solutions/ohip-billing/patient-care': { eyebrow: 'OHIP Billing · Patient Care', title: 'Streamline rostering and patient recall.', intro: 'Patient Care provides an end-to-end rostering and recall solution that supports better patient management and revenue potential.', image: '/young-nurse-white-uniform-checks-patient-with-stethoscope-front-view.jpg', points: ['Roster monitoring and alerts', 'Patient recall support', 'Preventive care program coordination'], sectionTitle: 'Better care, better practice management.', sectionText: 'Keep your patient panel organized and make preventive care activities easier to manage.' },
  'solutions/msp-billing': { eyebrow: 'MSP Billing', title: 'Simplify your MSP billing and reporting.', intro: 'Get support for billing submissions, error reconciliation, reporting, and the administrative work that takes time away from your patients.', image: '/front-view-male-doctor-medical-suit-with-stethoscope-blue-surface.jpg', points: ['MSP claim management', 'Error reconciliation', 'Reporting and revenue oversight'], sectionTitle: 'Confident MSP billing support.', sectionText: 'A focused billing process helps your BC practice stay organized and capture the revenue it has earned.' },
  'solutions/ahcip-billing': { eyebrow: 'AHCIP Billing', title: 'Full-service AHCIP billing support.', intro: 'Focus on patient care while our team supports Alberta billing, payment model changes, and the details that keep revenue on track.', image: '/medium-shot-smiley-doctor-holding-tablet.jpg', points: ['Full-service AHCIP billing', 'Payment model transition support', 'Revenue optimization and reporting'], sectionTitle: 'Billing support for Alberta physicians.', sectionText: 'Bring more confidence and less administrative burden to your Alberta billing workflow.' },
  'solutions/other-provinces': { eyebrow: 'Other Provinces', title: 'Medical billing support across Canada.', intro: 'We support physicians in Saskatchewan, Manitoba, and other provinces with billing management and revenue optimization services.', image: '/young-nurse-face-mask-hand-gloves-checks-patient-with-stethoscope.jpg', points: ['Flexible, province-aware support', 'A workflow that works with your practice', 'Revenue-focused billing management'], sectionTitle: 'Support wherever you practise.', sectionText: 'Our approach adapts to your billing environment, so your practice gets the help it needs without unnecessary complexity.' },
}

const codeLinks = [
  ['AHCIP', 'Alberta Health Billing Codes', 'https://www.dr-bill.ca/alberta-health-billing-codes'], ['AHCIP', 'Alberta Health Explanatory Codes', 'https://www.dr-bill.ca/alberta-health-billing-explanatory-codes-2'], ['AHCIP', 'Service Codes & Modifier Definitions', 'https://www.dr-bill.ca/blog/ahcip/alberta-health-service-codes-modifier-definitions'], ['MSP', 'MSP Billing Codes', 'https://www.dr-bill.ca/msp_billing_codes'], ['MSP', 'MSP Billing Explanatory Codes', 'https://www.dr-bill.ca/msp-billing-explanatory-codes'], ['MSP', 'MSP Cut-off Dates', 'https://www.dr-bill.ca/msp-cut-off-dates'], ['OHIP', 'OHIP Billing Codes', 'https://www.dr-bill.ca/ohip_billing_codes'], ['OHIP', 'OHIP Diagnostic Codes', 'https://www.dr-bill.ca/ohip-diagnostic-codes'], ['OHIP', 'OHIP Billing Error Codes', 'https://www.dr-bill.ca/ohip-billing-error-codes'], ['OHIP', 'OHIP Cut-off Dates', 'https://www.dr-bill.ca/ohip-cut-off-dates'],
]

function CodePage() { return <><Header /><main className="bg-[#fbf9fb]"><section className="bg-[#2b1527] px-6 py-24 text-white lg:py-32"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#e9b5d7]">Billing resources</p><h1 className="mt-5 max-w-3xl text-5xl font-extrabold tracking-tight md:text-7xl">Provincial billing codes, in one place.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">Quick links to essential AHCIP, MSP, and OHIP billing code resources for Canadian physicians and clinic teams.</p></div></section><section className="mx-auto max-w-7xl px-6 py-20"><div className="grid gap-7 md:grid-cols-3">{['AHCIP', 'MSP', 'OHIP'].map(group => <div key={group} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-2xl font-bold text-[#7e0e58]">{group}</h2><div className="mt-6 grid gap-3">{codeLinks.filter(x => x[0] === group).map(([, title, href]) => <a key={href} target="_blank" rel="noreferrer" href={href} className="group flex items-start justify-between gap-3 border-b border-slate-100 pb-3 text-sm font-semibold text-slate-700 hover:text-[#7e0e58]">{title}<ArrowRight className="h-4 w-4 shrink-0 transition group-hover:translate-x-1"/></a>)}</div></div>)}</div></section></main><Footer /></> }

export default async function ServicePage({ params }: { params: Promise<{ locale: string; slug: string[] }> }) {
  const { locale, slug } = await params; const key = slug.join('/')
  if (key === 'code') return <CodePage />
  const page = content[key] ?? content['solutions']; const services = key.startsWith('billing-services')
  return <><Header /><main className="overflow-hidden bg-white"><section className="relative bg-[#f8f3f7] px-6 pb-20 pt-20 lg:pb-28 lg:pt-28"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#7e0e58]">{page.eyebrow}</p><h1 className="mt-5 text-5xl font-extrabold leading-[.98] tracking-tight text-slate-900 md:text-6xl lg:text-7xl">{page.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">{page.intro}</p><Link href="#contact" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#7e0e58] px-6 py-3.5 font-bold text-white hover:bg-[#680847]">Book a free assessment <ArrowRight className="h-4 w-4"/></Link></div><div className="relative min-h-[350px] overflow-hidden rounded-[2rem] shadow-xl"><Image src={page.image} alt="Canadian healthcare professional" fill priority className="object-cover"/><div className="absolute inset-0 bg-gradient-to-tr from-[#7e0e58]/25 to-transparent"/></div></div></section><section className="mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-[.8fr_1.2fr] lg:py-28"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#7e0e58]">How we help</p><h2 className="mt-4 text-4xl font-extrabold tracking-tight text-slate-900 md:text-5xl">{page.sectionTitle}</h2></div><div><p className="text-lg leading-8 text-slate-600">{page.sectionText}</p><div className="mt-9 grid gap-4 sm:grid-cols-2">{page.points.map(point => <div key={point} className="flex gap-3 rounded-xl bg-slate-50 p-4 text-sm font-semibold leading-6 text-slate-700"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-[#7e0e58]"/>{point}</div>)}</div></div></section><section className="bg-[#7e0e58] px-6 py-16 text-center text-white"><p className="text-sm font-bold uppercase tracking-[.18em] text-white/60">GNF Billing</p><h2 className="mx-auto mt-3 max-w-2xl text-4xl font-extrabold tracking-tight">Relieve the stress of billing complexity.</h2><p className="mx-auto mt-4 max-w-xl text-white/75">Get started with a free billing assessment and a clearer path to optimized revenue.</p><Link href="#contact" className="mt-7 inline-flex rounded-full bg-white px-6 py-3 font-bold text-[#7e0e58]">Get started today</Link></section></main><Footer /></>
}
