// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/[...slug]" | "/[locale]/billing-services" | "/[locale]/billing-services/billing-care" | "/[locale]/billing-services/billing-care-plus" | "/[locale]/billing-services/practice-care" | "/[locale]/billing-services/uninsured-medical-services" | "/[locale]/blog" | "/[locale]/blog/[slug]" | "/[locale]/documentation" | "/[locale]/solo-billing" | "/[locale]/solutions" | "/[locale]/solutions/ahcip-billing" | "/[locale]/solutions/msp-billing" | "/[locale]/solutions/ohip-billing" | "/[locale]/solutions/ohip-billing/discover-practice-care" | "/[locale]/solutions/ohip-billing/ohip-billing-services-for-specialists" | "/[locale]/solutions/ohip-billing/patient-care" | "/[locale]/solutions/ohip-billing/physician-transition-services" | "/[locale]/solutions/ohip-billing/transitioning-to-fho" | "/[locale]/solutions/other-provinces" | "/[locale]/solutions/other-provinces/manitoba-billing" | "/[locale]/solutions/other-provinces/ramq-billing"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/[...slug]": { "locale": string; "slug": string[]; }
  "/[locale]/billing-services": { "locale": string; }
  "/[locale]/billing-services/billing-care": { "locale": string; }
  "/[locale]/billing-services/billing-care-plus": { "locale": string; }
  "/[locale]/billing-services/practice-care": { "locale": string; }
  "/[locale]/billing-services/uninsured-medical-services": { "locale": string; }
  "/[locale]/blog": { "locale": string; }
  "/[locale]/blog/[slug]": { "locale": string; "slug": string; }
  "/[locale]/documentation": { "locale": string; }
  "/[locale]/solo-billing": { "locale": string; }
  "/[locale]/solutions": { "locale": string; }
  "/[locale]/solutions/ahcip-billing": { "locale": string; }
  "/[locale]/solutions/msp-billing": { "locale": string; }
  "/[locale]/solutions/ohip-billing": { "locale": string; }
  "/[locale]/solutions/ohip-billing/discover-practice-care": { "locale": string; }
  "/[locale]/solutions/ohip-billing/ohip-billing-services-for-specialists": { "locale": string; }
  "/[locale]/solutions/ohip-billing/patient-care": { "locale": string; }
  "/[locale]/solutions/ohip-billing/physician-transition-services": { "locale": string; }
  "/[locale]/solutions/ohip-billing/transitioning-to-fho": { "locale": string; }
  "/[locale]/solutions/other-provinces": { "locale": string; }
  "/[locale]/solutions/other-provinces/manitoba-billing": { "locale": string; }
  "/[locale]/solutions/other-provinces/ramq-billing": { "locale": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
