// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/[locale]/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/[...slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/billing-services/billing-care-plus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/billing-services/billing-care-plus">> = Specific
  const handler = {} as typeof import("../../app/[locale]/billing-services/billing-care-plus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/billing-services/billing-care/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/billing-services/billing-care">> = Specific
  const handler = {} as typeof import("../../app/[locale]/billing-services/billing-care/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/billing-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/billing-services">> = Specific
  const handler = {} as typeof import("../../app/[locale]/billing-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/billing-services/practice-care/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/billing-services/practice-care">> = Specific
  const handler = {} as typeof import("../../app/[locale]/billing-services/practice-care/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/billing-services/uninsured-medical-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/billing-services/uninsured-medical-services">> = Specific
  const handler = {} as typeof import("../../app/[locale]/billing-services/uninsured-medical-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../app/[locale]/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/documentation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/documentation">> = Specific
  const handler = {} as typeof import("../../app/[locale]/documentation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solo-billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solo-billing">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solo-billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/ahcip-billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/ahcip-billing">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/ahcip-billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/msp-billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/msp-billing">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/msp-billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/ohip-billing/discover-practice-care/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/ohip-billing/discover-practice-care">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/ohip-billing/discover-practice-care/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/ohip-billing/ohip-billing-services-for-specialists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/ohip-billing/ohip-billing-services-for-specialists">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/ohip-billing/ohip-billing-services-for-specialists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/ohip-billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/ohip-billing">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/ohip-billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/ohip-billing/patient-care/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/ohip-billing/patient-care">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/ohip-billing/patient-care/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/ohip-billing/physician-transition-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/ohip-billing/physician-transition-services">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/ohip-billing/physician-transition-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/ohip-billing/transitioning-to-fho/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/ohip-billing/transitioning-to-fho">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/ohip-billing/transitioning-to-fho/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/other-provinces/manitoba-billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/other-provinces/manitoba-billing">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/other-provinces/manitoba-billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/other-provinces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/other-provinces">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/other-provinces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/other-provinces/ramq-billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions/other-provinces/ramq-billing">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/other-provinces/ramq-billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/solutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/solutions">> = Specific
  const handler = {} as typeof import("../../app/[locale]/solutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
