module.exports=[77818,a=>{"use strict";a.s(["Analytics",()=>b]);let b=(0,a.i(99457).registerClientReference)(function(){throw Error("Attempted to call Analytics() from the server but Analytics is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/Desktop/pitch/GNF/node_modules/@vercel/analytics/dist/next/index.mjs <module evaluation>","Analytics")},17676,a=>{"use strict";a.s(["Analytics",()=>b]);let b=(0,a.i(99457).registerClientReference)(function(){throw Error("Attempted to call Analytics() from the server but Analytics is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/Desktop/pitch/GNF/node_modules/@vercel/analytics/dist/next/index.mjs","Analytics")},51696,a=>{"use strict";a.i(77818);var b=a.i(17676);a.n(b)},89578,a=>{a.v({className:"geist_a71539c9-module__T19VSG__className",variable:"geist_a71539c9-module__T19VSG__variable"})},35214,a=>{a.v({className:"geist_mono_8d43a2aa-module__8Li5zG__className",variable:"geist_mono_8d43a2aa-module__8Li5zG__variable"})},45444,a=>{"use strict";a.s(["default",()=>b]);let b=(0,a.i(99457).registerClientReference)(function(){throw Error("Attempted to call the default export of [project]/Desktop/pitch/GNF/components/providers.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/Desktop/pitch/GNF/components/providers.tsx <module evaluation>","default")},62070,a=>{"use strict";a.s(["default",()=>b]);let b=(0,a.i(99457).registerClientReference)(function(){throw Error("Attempted to call the default export of [project]/Desktop/pitch/GNF/components/providers.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/Desktop/pitch/GNF/components/providers.tsx","default")},72355,a=>{"use strict";a.i(45444);var b=a.i(62070);a.n(b)},32913,a=>{"use strict";var b=a.i(46462),c=a.i(51696),d=a.i(89578);let e={className:d.default.className,style:{fontFamily:"'Geist', 'Geist Fallback'",fontStyle:"normal"}};null!=d.default.variable&&(e.variable=d.default.variable);var f=a.i(35214);let g={className:f.default.className,style:{fontFamily:"'Geist Mono', 'Geist Mono Fallback'",fontStyle:"normal"}};null!=f.default.variable&&(g.variable=f.default.variable);var h=a.i(72355);a.s(["default",0,function({children:a}){return(0,b.jsx)("html",{lang:"en",suppressHydrationWarning:!0,children:(0,b.jsxs)("body",{className:`
          ${e.variable}
          ${g.variable}
          font-sans
          antialiased
          bg-white
          dark:bg-slate-950
          transition-colors
        `,children:[(0,b.jsx)(h.default,{children:a}),(0,b.jsx)(c.Analytics,{})]})})},"metadata",0,{title:"Canadian Healthcare Billing Solutions | RCM Services for Healthcare Providers",description:"Streamlined RCM solutions for Canadian healthcare providers. OHIP, MSP, RAMQ, and provincial compliance.",generator:"GNF-Billing"}],32913)},74468,a=>{a.n(a.i(32913))}];

//# sourceMappingURL=%5Broot-of-the-server%5D__07hot7e._.js.map